import { Product } from "@shared/types";

export const sampleProducts: Product[] = [
  {
    id: "1",
    name: "Premium Cotton T-Shirt - Comfortable Everyday Wear",
    description:
      "High-quality premium cotton t-shirt perfect for everyday wear. Made from 100% organic cotton with a soft, breathable fabric that gets better with every wash.",
    images: [
      "/placeholder.svg",
      "/placeholder.svg",
      "/placeholder.svg",
      "/placeholder.svg",
      "/placeholder.svg",
    ],
    mrp: 899,
    ourPrice: 599,
    discount: 33,
    rating: 4.3,
    afterExchangePrice: 549,
    offers: ["Buy 2 Get 1 Free", "Free Shipping"],
    coupons: ["SAVE20", "FIRST100"],
    company: "FashionHub",
    color: "Blue",
    size: "L",
    weight: "200g",
    height: "70cm",
    category: "clothes",
    inStock: true,
    reviews: [],
    faqs: [
      {
        id: "1",
        question: "What is the fabric material?",
        answer: "100% organic cotton",
      },
    ],
  },
  {
    id: "2",
    name: "Wireless Gaming Mouse - High Precision 8000 DPI",
    description:
      "Professional wireless gaming mouse with 8000 DPI precision sensor. Perfect for gaming and professional work with ergonomic design.",
    images: [
      "/placeholder.svg",
      "/placeholder.svg",
      "/placeholder.svg",
      "/placeholder.svg",
      "/placeholder.svg",
    ],
    mrp: 2999,
    ourPrice: 1899,
    discount: 37,
    rating: 4.6,
    afterExchangePrice: 1799,
    offers: ["1 Year Warranty", "Free Shipping"],
    coupons: ["TECH15", "GAMING50"],
    company: "TechMaster",
    color: "Black",
    size: "Standard",
    weight: "120g",
    height: "4cm",
    category: "mice",
    inStock: true,
    reviews: [],
    faqs: [
      {
        id: "1",
        question: "What is the battery life?",
        answer: "Up to 70 hours of continuous use",
      },
    ],
  },
  {
    id: "3",
    name: "Anti-Aging Face Serum with Vitamin C - 30ml",
    description:
      "Premium anti-aging face serum enriched with Vitamin C and hyaluronic acid. Reduces fine lines and gives you glowing, youthful skin.",
    images: [
      "/placeholder.svg",
      "/placeholder.svg",
      "/placeholder.svg",
      "/placeholder.svg",
      "/placeholder.svg",
    ],
    mrp: 1499,
    ourPrice: 999,
    discount: 33,
    rating: 4.4,
    afterExchangePrice: 949,
    offers: ["Dermatologist Tested", "Free Shipping"],
    coupons: ["BEAUTY20", "GLOW15"],
    company: "GlowCare",
    color: "Clear",
    size: "30ml",
    weight: "50g",
    height: "12cm",
    category: "beauty",
    inStock: true,
    reviews: [],
    faqs: [
      {
        id: "1",
        question: "Is it suitable for sensitive skin?",
        answer:
          "Yes, it's dermatologist tested and suitable for all skin types",
      },
    ],
  },
  {
    id: "4",
    name: "4K Ultra HD Smart TV - 55 Inch LED Display",
    description:
      "Ultra HD 4K Smart TV with HDR support and built-in streaming apps. Perfect for entertainment with crystal clear picture quality.",
    images: [
      "/placeholder.svg",
      "/placeholder.svg",
      "/placeholder.svg",
      "/placeholder.svg",
      "/placeholder.svg",
    ],
    mrp: 54999,
    ourPrice: 39999,
    discount: 27,
    rating: 4.5,
    afterExchangePrice: 37999,
    offers: ["2 Year Warranty", "Free Installation"],
    coupons: ["TV5000", "ELECTRONICS10"],
    company: "VisionTech",
    color: "Black",
    size: "55 inch",
    weight: "18kg",
    height: "76cm",
    category: "electronics",
    inStock: true,
    reviews: [],
    faqs: [
      {
        id: "1",
        question: "Does it support HDR?",
        answer: "Yes, it supports HDR10 and Dolby Vision",
      },
    ],
  },
  {
    id: "5",
    name: "The Complete Guide to Web Development - Latest Edition",
    description:
      "Comprehensive guide to modern web development covering HTML, CSS, JavaScript, React, and Node.js. Perfect for beginners and professionals.",
    images: [
      "/placeholder.svg",
      "/placeholder.svg",
      "/placeholder.svg",
      "/placeholder.svg",
      "/placeholder.svg",
    ],
    mrp: 799,
    ourPrice: 599,
    discount: 25,
    rating: 4.7,
    afterExchangePrice: 579,
    offers: ["Digital Copy Included", "Free Shipping"],
    coupons: ["BOOK15", "LEARN20"],
    company: "TechBooks",
    color: "Blue",
    size: "A5",
    weight: "500g",
    height: "2.5cm",
    category: "books",
    inStock: true,
    reviews: [],
    faqs: [
      {
        id: "1",
        question: "Is the digital copy included?",
        answer: "Yes, you get both physical and digital copies",
      },
    ],
  },
  {
    id: "6",
    name: "Organic Basmati Rice - Premium Quality 5kg",
    description:
      "Premium quality organic basmati rice sourced directly from farmers. Long grain, aromatic rice perfect for biryanis and daily meals.",
    images: [
      "/placeholder.svg",
      "/placeholder.svg",
      "/placeholder.svg",
      "/placeholder.svg",
      "/placeholder.svg",
    ],
    mrp: 899,
    ourPrice: 749,
    discount: 17,
    rating: 4.2,
    afterExchangePrice: 729,
    offers: ["Organic Certified", "Same Day Delivery"],
    coupons: ["GROCERY10", "ORGANIC15"],
    company: "FarmFresh",
    color: "White",
    size: "5kg",
    weight: "5kg",
    height: "35cm",
    category: "groceries",
    inStock: true,
    reviews: [],
    faqs: [
      {
        id: "1",
        question: "Is it pesticide-free?",
        answer: "Yes, it's 100% organic and pesticide-free",
      },
    ],
  },
];
